### ISSUE TITLE
Add "making a plugin" tutorial + Update "The Plugin System" tutorial on OM website

### ISSUE THREAD

**Issue by PaperPrototype** [OurMachinery/themachinery-books#1]
The OM website has a Tutorial https://ourmachinery.com/tutorials/the-plugin-system/ called "The Plugin System". It would be nice if it was hosted on this repo.

Also I think it would be useful if the tutorial were a bit more pragmatic -> the tutorial guides you through making a simple example plugin. Also have example plugin use other plugins.

**Comment by simon-ourmachinery** [comment]
It is already there in the general `the-machinery-book` [here](https://ourmachinery.github.io/themachinery-books/the_machinery_book/extending_the_machinery/the_plugin_system.html)

**Comment by PaperPrototype** [comment]
@simon-ourmachinery Ah, thanks! ^^
