### ISSUE TITLE
Broken link in the_truth/custom_asset/part1.md

### ISSUE THREAD

**Issue by Selmar** [OurMachinery/themachinery-books#24]
[the_truth/custom_asset/part1.md](https://github.com/OurMachinery/themachinery-books/blob/main/tutorials/src/the_truth/custom_asset/part1.md)

![image](https://user-images.githubusercontent.com/3010534/151389574-b99a976a-6159-42ab-a9ea-f7fec020cfd2.png)

I didn't find the place where the link leads to so I couldn't fix it myself.

**Comment by simon-ourmachinery** [comment]
thanks for the infos I will check them asp
