### ISSUE TITLE
CSS files from ourmachinery.com not loading correctly in Firefox

### ISSUE THREAD

**Issue by ForxVT** [OurMachinery/themachinery-books#6]
It seems that on the index page of the website while the CSS files [https://ourmachinery.com/css/bootstrap.min.css](https://ourmachinery.com/css/bootstrap.min.css) and [https://ourmachinery.com/css/style.min.css](https://ourmachinery.com/css/style.min.css) are loaded correctly in Chrome (I haven't tested anything else than Chrome and Firefox), they do not load on Firefox. Resulting in a quite bare bone result:

![ren](https://user-images.githubusercontent.com/12241801/125675479-366c710b-3b6f-41e3-9d61-6205eafdc511.png)

It seems to be an issue with the CORS headers within the [ourmachinery.com](ourmachinery.com) website by looking at the console errors.

![err](https://user-images.githubusercontent.com/12241801/125675728-3a072a18-98b1-44e2-9f67-3b651887a63b.png)

More info about it can be found [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin) if it help!

**Comment by simon-ourmachinery** [comment]
Thank you very much!

**Comment by simon-ourmachinery** [comment]
@ForxVT please lemme know if this is not fixed

**Comment by ForxVT** [comment]
Working as expected! Thank you.

**Comment by simon-ourmachinery** [comment]
no worries! feel free to comment on whatever is needed/missing either here or https://github.com/OurMachinery/themachinery-public/discussions/596
