### ISSUE TITLE
The Truth Access Values Extra Argument in Example

### ISSUE THREAD

**Issue by borkin8r** [OurMachinery/themachinery-books#7]
I was reading the section about[ Accessing Values of The Truth](https://ourmachinery.github.io/themachinery-books/the_machinery_book/the_truth/access_values.html) and feel that I may be missing something.

The function signature for `get_float` has three arguments:
`void (*get_float)(tm_the_truth_o *tt,const tm_the_truth_object_o *obj, uint32_t property);
`
But the example uses four arguments:
```
void log_with(tm_the_truth_o *tt, tm_tt_id_t my_object){   
    const float wdith = tm_the_truth_api->get_float(tt,tm_tt_read(tt,my_object),my_object_w,TM_TT_PROP__RECT__W);
    TM_LOG("the width is %f",width);
}
```
I understand where all the arguments are from except `my_object_w`. Is it supposed to be in there? If so where does it come from?

Edit: grammar

**Comment by simon-ourmachinery** [comment]
No it is not supposed to be there. thanks for pointing this out. I made a mistake when creating it.
